// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.DocFilePreview in public_user_file.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class DocFilePreview(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val identity: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val parent: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val name: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val path: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mimeType",
    schemaIndex = 4,
  )
  public val mime_type: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val size: Long = 0L,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val type: Long = 0L,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "canPreview",
    schemaIndex = 7,
  )
  public val can_preview: Boolean = false,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "previewAddress",
    schemaIndex = 8,
  )
  public val preview_address: String = "",
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "previewToken",
    schemaIndex = 9,
  )
  public val preview_token: String = "",
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "canEdit",
    schemaIndex = 10,
  )
  public val can_edit: Boolean = false,
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "editAddress",
    schemaIndex = 11,
  )
  public val edit_address: String = "",
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "editToken",
    schemaIndex = 12,
  )
  public val edit_token: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DocFilePreview, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DocFilePreview) return false
    if (unknownFields != other.unknownFields) return false
    if (identity != other.identity) return false
    if (parent != other.parent) return false
    if (name != other.name) return false
    if (path != other.path) return false
    if (mime_type != other.mime_type) return false
    if (size != other.size) return false
    if (type != other.type) return false
    if (can_preview != other.can_preview) return false
    if (preview_address != other.preview_address) return false
    if (preview_token != other.preview_token) return false
    if (can_edit != other.can_edit) return false
    if (edit_address != other.edit_address) return false
    if (edit_token != other.edit_token) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + identity.hashCode()
      result = result * 37 + parent.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + path.hashCode()
      result = result * 37 + mime_type.hashCode()
      result = result * 37 + size.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + can_preview.hashCode()
      result = result * 37 + preview_address.hashCode()
      result = result * 37 + preview_token.hashCode()
      result = result * 37 + can_edit.hashCode()
      result = result * 37 + edit_address.hashCode()
      result = result * 37 + edit_token.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """identity=${sanitize(identity)}"""
    result += """parent=${sanitize(parent)}"""
    result += """name=${sanitize(name)}"""
    result += """path=${sanitize(path)}"""
    result += """mime_type=${sanitize(mime_type)}"""
    result += """size=$size"""
    result += """type=$type"""
    result += """can_preview=$can_preview"""
    result += """preview_address=${sanitize(preview_address)}"""
    result += """preview_token=${sanitize(preview_token)}"""
    result += """can_edit=$can_edit"""
    result += """edit_address=${sanitize(edit_address)}"""
    result += """edit_token=${sanitize(edit_token)}"""
    return result.joinToString(prefix = "DocFilePreview{", separator = ", ", postfix = "}")
  }

  public fun copy(
    identity: String = this.identity,
    parent: String = this.parent,
    name: String = this.name,
    path: String = this.path,
    mime_type: String = this.mime_type,
    size: Long = this.size,
    type: Long = this.type,
    can_preview: Boolean = this.can_preview,
    preview_address: String = this.preview_address,
    preview_token: String = this.preview_token,
    can_edit: Boolean = this.can_edit,
    edit_address: String = this.edit_address,
    edit_token: String = this.edit_token,
    unknownFields: ByteString = this.unknownFields,
  ): DocFilePreview = DocFilePreview(identity, parent, name, path, mime_type, size, type,
      can_preview, preview_address, preview_token, can_edit, edit_address, edit_token,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DocFilePreview> = object : ProtoAdapter<DocFilePreview>(
      FieldEncoding.LENGTH_DELIMITED, 
      DocFilePreview::class, 
      "type.googleapis.com/v6.services.pub.DocFilePreview", 
      PROTO_3, 
      null, 
      "public_user_file.proto"
    ) {
      override fun encodedSize(`value`: DocFilePreview): Int {
        var size_ = value.unknownFields.size
        if (value.identity != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(1, value.identity)
        if (value.parent != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(3, value.parent)
        if (value.name != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(4, value.name)
        if (value.path != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(5, value.path)
        if (value.mime_type != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(6,
            value.mime_type)
        if (value.size != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(7, value.size)
        if (value.type != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(8, value.type)
        if (value.can_preview != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(9,
            value.can_preview)
        if (value.preview_address != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(10,
            value.preview_address)
        if (value.preview_token != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(11,
            value.preview_token)
        if (value.can_edit != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(12,
            value.can_edit)
        if (value.edit_address != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(13,
            value.edit_address)
        if (value.edit_token != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(14,
            value.edit_token)
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: DocFilePreview) {
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
        if (value.parent != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.parent)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.name)
        if (value.path != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.path)
        if (value.mime_type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.mime_type)
        if (value.size != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.size)
        if (value.type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.type)
        if (value.can_preview != false) ProtoAdapter.BOOL.encodeWithTag(writer, 9,
            value.can_preview)
        if (value.preview_address != "") ProtoAdapter.STRING.encodeWithTag(writer, 10,
            value.preview_address)
        if (value.preview_token != "") ProtoAdapter.STRING.encodeWithTag(writer, 11,
            value.preview_token)
        if (value.can_edit != false) ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.can_edit)
        if (value.edit_address != "") ProtoAdapter.STRING.encodeWithTag(writer, 13,
            value.edit_address)
        if (value.edit_token != "") ProtoAdapter.STRING.encodeWithTag(writer, 14, value.edit_token)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DocFilePreview) {
        writer.writeBytes(value.unknownFields)
        if (value.edit_token != "") ProtoAdapter.STRING.encodeWithTag(writer, 14, value.edit_token)
        if (value.edit_address != "") ProtoAdapter.STRING.encodeWithTag(writer, 13,
            value.edit_address)
        if (value.can_edit != false) ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.can_edit)
        if (value.preview_token != "") ProtoAdapter.STRING.encodeWithTag(writer, 11,
            value.preview_token)
        if (value.preview_address != "") ProtoAdapter.STRING.encodeWithTag(writer, 10,
            value.preview_address)
        if (value.can_preview != false) ProtoAdapter.BOOL.encodeWithTag(writer, 9,
            value.can_preview)
        if (value.type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.type)
        if (value.size != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.size)
        if (value.mime_type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.mime_type)
        if (value.path != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.path)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.name)
        if (value.parent != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.parent)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
      }

      override fun decode(reader: ProtoReader): DocFilePreview {
        var identity: String = ""
        var parent: String = ""
        var name: String = ""
        var path: String = ""
        var mime_type: String = ""
        var size: Long = 0L
        var type: Long = 0L
        var can_preview: Boolean = false
        var preview_address: String = ""
        var preview_token: String = ""
        var can_edit: Boolean = false
        var edit_address: String = ""
        var edit_token: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> identity = ProtoAdapter.STRING.decode(reader)
            3 -> parent = ProtoAdapter.STRING.decode(reader)
            4 -> name = ProtoAdapter.STRING.decode(reader)
            5 -> path = ProtoAdapter.STRING.decode(reader)
            6 -> mime_type = ProtoAdapter.STRING.decode(reader)
            7 -> size = ProtoAdapter.INT64.decode(reader)
            8 -> type = ProtoAdapter.INT64.decode(reader)
            9 -> can_preview = ProtoAdapter.BOOL.decode(reader)
            10 -> preview_address = ProtoAdapter.STRING.decode(reader)
            11 -> preview_token = ProtoAdapter.STRING.decode(reader)
            12 -> can_edit = ProtoAdapter.BOOL.decode(reader)
            13 -> edit_address = ProtoAdapter.STRING.decode(reader)
            14 -> edit_token = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DocFilePreview(
          identity = identity,
          parent = parent,
          name = name,
          path = path,
          mime_type = mime_type,
          size = size,
          type = type,
          can_preview = can_preview,
          preview_address = preview_address,
          preview_token = preview_token,
          can_edit = can_edit,
          edit_address = edit_address,
          edit_token = edit_token,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DocFilePreview): DocFilePreview = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
