// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.DownloadAndPreviewInfo in public_user_file.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class DownloadAndPreviewInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val identity: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val parent: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val name: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val path: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mimeType",
    schemaIndex = 4,
  )
  public val mime_type: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val size: Long = 0L,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val type: Long = 0L,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "canPreview",
    schemaIndex = 7,
  )
  public val can_preview: Boolean = false,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "canEdit",
    schemaIndex = 8,
  )
  public val can_edit: Boolean = false,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "previewType",
    schemaIndex = 9,
  )
  public val preview_type: Int = 0,
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "downloadType",
    schemaIndex = 10,
  )
  public val download_type: Int = 0,
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 11,
  )
  public val sha1: String = "",
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "canDownload",
    schemaIndex = 12,
  )
  public val can_download: Boolean = false,
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "cannotDownloadMessage",
    schemaIndex = 13,
  )
  public val cannot_download_message: String = "",
  @field:WireField(
    tag = 16,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contentIdentity",
    schemaIndex = 14,
  )
  public val content_identity: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DownloadAndPreviewInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DownloadAndPreviewInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (identity != other.identity) return false
    if (parent != other.parent) return false
    if (name != other.name) return false
    if (path != other.path) return false
    if (mime_type != other.mime_type) return false
    if (size != other.size) return false
    if (type != other.type) return false
    if (can_preview != other.can_preview) return false
    if (can_edit != other.can_edit) return false
    if (preview_type != other.preview_type) return false
    if (download_type != other.download_type) return false
    if (sha1 != other.sha1) return false
    if (can_download != other.can_download) return false
    if (cannot_download_message != other.cannot_download_message) return false
    if (content_identity != other.content_identity) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + identity.hashCode()
      result = result * 37 + parent.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + path.hashCode()
      result = result * 37 + mime_type.hashCode()
      result = result * 37 + size.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + can_preview.hashCode()
      result = result * 37 + can_edit.hashCode()
      result = result * 37 + preview_type.hashCode()
      result = result * 37 + download_type.hashCode()
      result = result * 37 + sha1.hashCode()
      result = result * 37 + can_download.hashCode()
      result = result * 37 + cannot_download_message.hashCode()
      result = result * 37 + content_identity.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """identity=${sanitize(identity)}"""
    result += """parent=${sanitize(parent)}"""
    result += """name=${sanitize(name)}"""
    result += """path=${sanitize(path)}"""
    result += """mime_type=${sanitize(mime_type)}"""
    result += """size=$size"""
    result += """type=$type"""
    result += """can_preview=$can_preview"""
    result += """can_edit=$can_edit"""
    result += """preview_type=$preview_type"""
    result += """download_type=$download_type"""
    result += """sha1=${sanitize(sha1)}"""
    result += """can_download=$can_download"""
    result += """cannot_download_message=${sanitize(cannot_download_message)}"""
    result += """content_identity=${sanitize(content_identity)}"""
    return result.joinToString(prefix = "DownloadAndPreviewInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    identity: String = this.identity,
    parent: String = this.parent,
    name: String = this.name,
    path: String = this.path,
    mime_type: String = this.mime_type,
    size: Long = this.size,
    type: Long = this.type,
    can_preview: Boolean = this.can_preview,
    can_edit: Boolean = this.can_edit,
    preview_type: Int = this.preview_type,
    download_type: Int = this.download_type,
    sha1: String = this.sha1,
    can_download: Boolean = this.can_download,
    cannot_download_message: String = this.cannot_download_message,
    content_identity: String = this.content_identity,
    unknownFields: ByteString = this.unknownFields,
  ): DownloadAndPreviewInfo = DownloadAndPreviewInfo(identity, parent, name, path, mime_type, size,
      type, can_preview, can_edit, preview_type, download_type, sha1, can_download,
      cannot_download_message, content_identity, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DownloadAndPreviewInfo> = object :
        ProtoAdapter<DownloadAndPreviewInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      DownloadAndPreviewInfo::class, 
      "type.googleapis.com/v6.services.pub.DownloadAndPreviewInfo", 
      PROTO_3, 
      null, 
      "public_user_file.proto"
    ) {
      override fun encodedSize(`value`: DownloadAndPreviewInfo): Int {
        var size_ = value.unknownFields.size
        if (value.identity != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(1, value.identity)
        if (value.parent != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(3, value.parent)
        if (value.name != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(4, value.name)
        if (value.path != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(5, value.path)
        if (value.mime_type != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(6,
            value.mime_type)
        if (value.size != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(7, value.size)
        if (value.type != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(8, value.type)
        if (value.can_preview != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(9,
            value.can_preview)
        if (value.can_edit != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(10,
            value.can_edit)
        if (value.preview_type != 0) size_ += ProtoAdapter.INT32.encodedSizeWithTag(11,
            value.preview_type)
        if (value.download_type != 0) size_ += ProtoAdapter.INT32.encodedSizeWithTag(12,
            value.download_type)
        if (value.sha1 != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(13, value.sha1)
        if (value.can_download != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(14,
            value.can_download)
        if (value.cannot_download_message != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(15,
            value.cannot_download_message)
        if (value.content_identity != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(16,
            value.content_identity)
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: DownloadAndPreviewInfo) {
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
        if (value.parent != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.parent)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.name)
        if (value.path != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.path)
        if (value.mime_type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.mime_type)
        if (value.size != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.size)
        if (value.type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.type)
        if (value.can_preview != false) ProtoAdapter.BOOL.encodeWithTag(writer, 9,
            value.can_preview)
        if (value.can_edit != false) ProtoAdapter.BOOL.encodeWithTag(writer, 10, value.can_edit)
        if (value.preview_type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 11,
            value.preview_type)
        if (value.download_type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 12,
            value.download_type)
        if (value.sha1 != "") ProtoAdapter.STRING.encodeWithTag(writer, 13, value.sha1)
        if (value.can_download != false) ProtoAdapter.BOOL.encodeWithTag(writer, 14,
            value.can_download)
        if (value.cannot_download_message != "") ProtoAdapter.STRING.encodeWithTag(writer, 15,
            value.cannot_download_message)
        if (value.content_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 16,
            value.content_identity)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DownloadAndPreviewInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.content_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 16,
            value.content_identity)
        if (value.cannot_download_message != "") ProtoAdapter.STRING.encodeWithTag(writer, 15,
            value.cannot_download_message)
        if (value.can_download != false) ProtoAdapter.BOOL.encodeWithTag(writer, 14,
            value.can_download)
        if (value.sha1 != "") ProtoAdapter.STRING.encodeWithTag(writer, 13, value.sha1)
        if (value.download_type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 12,
            value.download_type)
        if (value.preview_type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 11,
            value.preview_type)
        if (value.can_edit != false) ProtoAdapter.BOOL.encodeWithTag(writer, 10, value.can_edit)
        if (value.can_preview != false) ProtoAdapter.BOOL.encodeWithTag(writer, 9,
            value.can_preview)
        if (value.type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.type)
        if (value.size != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.size)
        if (value.mime_type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.mime_type)
        if (value.path != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.path)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.name)
        if (value.parent != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.parent)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
      }

      override fun decode(reader: ProtoReader): DownloadAndPreviewInfo {
        var identity: String = ""
        var parent: String = ""
        var name: String = ""
        var path: String = ""
        var mime_type: String = ""
        var size: Long = 0L
        var type: Long = 0L
        var can_preview: Boolean = false
        var can_edit: Boolean = false
        var preview_type: Int = 0
        var download_type: Int = 0
        var sha1: String = ""
        var can_download: Boolean = false
        var cannot_download_message: String = ""
        var content_identity: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> identity = ProtoAdapter.STRING.decode(reader)
            3 -> parent = ProtoAdapter.STRING.decode(reader)
            4 -> name = ProtoAdapter.STRING.decode(reader)
            5 -> path = ProtoAdapter.STRING.decode(reader)
            6 -> mime_type = ProtoAdapter.STRING.decode(reader)
            7 -> size = ProtoAdapter.INT64.decode(reader)
            8 -> type = ProtoAdapter.INT64.decode(reader)
            9 -> can_preview = ProtoAdapter.BOOL.decode(reader)
            10 -> can_edit = ProtoAdapter.BOOL.decode(reader)
            11 -> preview_type = ProtoAdapter.INT32.decode(reader)
            12 -> download_type = ProtoAdapter.INT32.decode(reader)
            13 -> sha1 = ProtoAdapter.STRING.decode(reader)
            14 -> can_download = ProtoAdapter.BOOL.decode(reader)
            15 -> cannot_download_message = ProtoAdapter.STRING.decode(reader)
            16 -> content_identity = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DownloadAndPreviewInfo(
          identity = identity,
          parent = parent,
          name = name,
          path = path,
          mime_type = mime_type,
          size = size,
          type = type,
          can_preview = can_preview,
          can_edit = can_edit,
          preview_type = preview_type,
          download_type = download_type,
          sha1 = sha1,
          can_download = can_download,
          cannot_download_message = cannot_download_message,
          content_identity = content_identity,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DownloadAndPreviewInfo): DownloadAndPreviewInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
