// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.FastLookupRequest in slice_svc.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class FastLookupRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "v6.services.pub.FastLookup#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val info: FastLookup? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<FastLookupRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FastLookupRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (info != other.info) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + (info?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=$type"""
    if (info != null) result += """info=$info"""
    return result.joinToString(prefix = "FastLookupRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: Int = this.type,
    info: FastLookup? = this.info,
    unknownFields: ByteString = this.unknownFields,
  ): FastLookupRequest = FastLookupRequest(type, info, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FastLookupRequest> = object : ProtoAdapter<FastLookupRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      FastLookupRequest::class, 
      "type.googleapis.com/v6.services.pub.FastLookupRequest", 
      PROTO_3, 
      null, 
      "slice_svc.proto"
    ) {
      override fun encodedSize(`value`: FastLookupRequest): Int {
        var size = value.unknownFields.size
        if (value.type != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.type)
        if (value.info != null) size += FastLookup.ADAPTER.encodedSizeWithTag(2, value.info)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FastLookupRequest) {
        if (value.type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.type)
        if (value.info != null) FastLookup.ADAPTER.encodeWithTag(writer, 2, value.info)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FastLookupRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.info != null) FastLookup.ADAPTER.encodeWithTag(writer, 2, value.info)
        if (value.type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 1, value.type)
      }

      override fun decode(reader: ProtoReader): FastLookupRequest {
        var type: Int = 0
        var info: FastLookup? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.INT32.decode(reader)
            2 -> info = FastLookup.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return FastLookupRequest(
          type = type,
          info = info,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FastLookupRequest): FastLookupRequest = value.copy(
        info = value.info?.let(FastLookup.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
