// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.File in public_user_file.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class File(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val identity: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val parent: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val name: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val path: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mimeType",
    schemaIndex = 4,
  )
  public val mime_type: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val size: Long = 0L,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val type: Long = 0L,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "createTs",
    schemaIndex = 7,
  )
  public val create_ts: Long = 0L,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "updateTs",
    schemaIndex = 8,
  )
  public val update_ts: Long = 0L,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deleteTs",
    schemaIndex = 9,
  )
  public val delete_ts: Long = 0L,
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val deleted: Boolean = false,
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 11,
  )
  public val dir: Boolean = false,
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 12,
  )
  public val hidden: Boolean = false,
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 13,
  )
  public val locked: Boolean = false,
  @field:WireField(
    tag = 16,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 14,
  )
  public val shared: Boolean = false,
  @field:WireField(
    tag = 17,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 15,
  )
  public val starred: Boolean = false,
  @field:WireField(
    tag = 18,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 16,
  )
  public val trashed: Boolean = false,
  @field:WireField(
    tag = 19,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lockedAt",
    schemaIndex = 17,
  )
  public val locked_at: Long = 0L,
  @field:WireField(
    tag = 20,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lockedBy",
    schemaIndex = 18,
  )
  public val locked_by: String = "",
  @field:WireField(
    tag = 21,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sharedAt",
    schemaIndex = 19,
  )
  public val shared_at: Long = 0L,
  @field:WireField(
    tag = 22,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 20,
  )
  public val flag: Long = 0L,
  @field:WireField(
    tag = 23,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 21,
  )
  public val unique: String = "",
  @field:WireField(
    tag = 24,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contentIdentity",
    schemaIndex = 22,
  )
  public val content_identity: String = "",
  @field:WireField(
    tag = 25,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 23,
  )
  public val label: Long = 0L,
  @field:WireField(
    tag = 26,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "storeType",
    schemaIndex = 24,
  )
  public val store_type: Long = 0L,
  @field:WireField(
    tag = 27,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 25,
  )
  public val version: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<File, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is File) return false
    if (unknownFields != other.unknownFields) return false
    if (identity != other.identity) return false
    if (parent != other.parent) return false
    if (name != other.name) return false
    if (path != other.path) return false
    if (mime_type != other.mime_type) return false
    if (size != other.size) return false
    if (type != other.type) return false
    if (create_ts != other.create_ts) return false
    if (update_ts != other.update_ts) return false
    if (delete_ts != other.delete_ts) return false
    if (deleted != other.deleted) return false
    if (dir != other.dir) return false
    if (hidden != other.hidden) return false
    if (locked != other.locked) return false
    if (shared != other.shared) return false
    if (starred != other.starred) return false
    if (trashed != other.trashed) return false
    if (locked_at != other.locked_at) return false
    if (locked_by != other.locked_by) return false
    if (shared_at != other.shared_at) return false
    if (flag != other.flag) return false
    if (unique != other.unique) return false
    if (content_identity != other.content_identity) return false
    if (label != other.label) return false
    if (store_type != other.store_type) return false
    if (version != other.version) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + identity.hashCode()
      result = result * 37 + parent.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + path.hashCode()
      result = result * 37 + mime_type.hashCode()
      result = result * 37 + size.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + create_ts.hashCode()
      result = result * 37 + update_ts.hashCode()
      result = result * 37 + delete_ts.hashCode()
      result = result * 37 + deleted.hashCode()
      result = result * 37 + dir.hashCode()
      result = result * 37 + hidden.hashCode()
      result = result * 37 + locked.hashCode()
      result = result * 37 + shared.hashCode()
      result = result * 37 + starred.hashCode()
      result = result * 37 + trashed.hashCode()
      result = result * 37 + locked_at.hashCode()
      result = result * 37 + locked_by.hashCode()
      result = result * 37 + shared_at.hashCode()
      result = result * 37 + flag.hashCode()
      result = result * 37 + unique.hashCode()
      result = result * 37 + content_identity.hashCode()
      result = result * 37 + label.hashCode()
      result = result * 37 + store_type.hashCode()
      result = result * 37 + version.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """identity=${sanitize(identity)}"""
    result += """parent=${sanitize(parent)}"""
    result += """name=${sanitize(name)}"""
    result += """path=${sanitize(path)}"""
    result += """mime_type=${sanitize(mime_type)}"""
    result += """size=$size"""
    result += """type=$type"""
    result += """create_ts=$create_ts"""
    result += """update_ts=$update_ts"""
    result += """delete_ts=$delete_ts"""
    result += """deleted=$deleted"""
    result += """dir=$dir"""
    result += """hidden=$hidden"""
    result += """locked=$locked"""
    result += """shared=$shared"""
    result += """starred=$starred"""
    result += """trashed=$trashed"""
    result += """locked_at=$locked_at"""
    result += """locked_by=${sanitize(locked_by)}"""
    result += """shared_at=$shared_at"""
    result += """flag=$flag"""
    result += """unique=${sanitize(unique)}"""
    result += """content_identity=${sanitize(content_identity)}"""
    result += """label=$label"""
    result += """store_type=$store_type"""
    result += """version=$version"""
    return result.joinToString(prefix = "File{", separator = ", ", postfix = "}")
  }

  public fun copy(
    identity: String = this.identity,
    parent: String = this.parent,
    name: String = this.name,
    path: String = this.path,
    mime_type: String = this.mime_type,
    size: Long = this.size,
    type: Long = this.type,
    create_ts: Long = this.create_ts,
    update_ts: Long = this.update_ts,
    delete_ts: Long = this.delete_ts,
    deleted: Boolean = this.deleted,
    dir: Boolean = this.dir,
    hidden: Boolean = this.hidden,
    locked: Boolean = this.locked,
    shared: Boolean = this.shared,
    starred: Boolean = this.starred,
    trashed: Boolean = this.trashed,
    locked_at: Long = this.locked_at,
    locked_by: String = this.locked_by,
    shared_at: Long = this.shared_at,
    flag: Long = this.flag,
    unique: String = this.unique,
    content_identity: String = this.content_identity,
    label: Long = this.label,
    store_type: Long = this.store_type,
    version: Long = this.version,
    unknownFields: ByteString = this.unknownFields,
  ): File = File(identity, parent, name, path, mime_type, size, type, create_ts, update_ts,
      delete_ts, deleted, dir, hidden, locked, shared, starred, trashed, locked_at, locked_by,
      shared_at, flag, unique, content_identity, label, store_type, version, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<File> = object : ProtoAdapter<File>(
      FieldEncoding.LENGTH_DELIMITED, 
      File::class, 
      "type.googleapis.com/v6.services.pub.File", 
      PROTO_3, 
      null, 
      "public_user_file.proto"
    ) {
      override fun encodedSize(`value`: File): Int {
        var size_ = value.unknownFields.size
        if (value.identity != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(1, value.identity)
        if (value.parent != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(3, value.parent)
        if (value.name != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(4, value.name)
        if (value.path != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(5, value.path)
        if (value.mime_type != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(6,
            value.mime_type)
        if (value.size != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(7, value.size)
        if (value.type != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(8, value.type)
        if (value.create_ts != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(9,
            value.create_ts)
        if (value.update_ts != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(10,
            value.update_ts)
        if (value.delete_ts != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(11,
            value.delete_ts)
        if (value.deleted != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(12, value.deleted)
        if (value.dir != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(13, value.dir)
        if (value.hidden != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(14, value.hidden)
        if (value.locked != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(15, value.locked)
        if (value.shared != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(16, value.shared)
        if (value.starred != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(17, value.starred)
        if (value.trashed != false) size_ += ProtoAdapter.BOOL.encodedSizeWithTag(18, value.trashed)
        if (value.locked_at != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(19,
            value.locked_at)
        if (value.locked_by != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(20,
            value.locked_by)
        if (value.shared_at != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(21,
            value.shared_at)
        if (value.flag != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(22, value.flag)
        if (value.unique != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(23, value.unique)
        if (value.content_identity != "") size_ += ProtoAdapter.STRING.encodedSizeWithTag(24,
            value.content_identity)
        if (value.label != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(25, value.label)
        if (value.store_type != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(26,
            value.store_type)
        if (value.version != 0L) size_ += ProtoAdapter.INT64.encodedSizeWithTag(27, value.version)
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: File) {
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
        if (value.parent != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.parent)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.name)
        if (value.path != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.path)
        if (value.mime_type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.mime_type)
        if (value.size != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.size)
        if (value.type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.type)
        if (value.create_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 9, value.create_ts)
        if (value.update_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 10, value.update_ts)
        if (value.delete_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 11, value.delete_ts)
        if (value.deleted != false) ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.deleted)
        if (value.dir != false) ProtoAdapter.BOOL.encodeWithTag(writer, 13, value.dir)
        if (value.hidden != false) ProtoAdapter.BOOL.encodeWithTag(writer, 14, value.hidden)
        if (value.locked != false) ProtoAdapter.BOOL.encodeWithTag(writer, 15, value.locked)
        if (value.shared != false) ProtoAdapter.BOOL.encodeWithTag(writer, 16, value.shared)
        if (value.starred != false) ProtoAdapter.BOOL.encodeWithTag(writer, 17, value.starred)
        if (value.trashed != false) ProtoAdapter.BOOL.encodeWithTag(writer, 18, value.trashed)
        if (value.locked_at != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 19, value.locked_at)
        if (value.locked_by != "") ProtoAdapter.STRING.encodeWithTag(writer, 20, value.locked_by)
        if (value.shared_at != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 21, value.shared_at)
        if (value.flag != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 22, value.flag)
        if (value.unique != "") ProtoAdapter.STRING.encodeWithTag(writer, 23, value.unique)
        if (value.content_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 24,
            value.content_identity)
        if (value.label != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 25, value.label)
        if (value.store_type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 26, value.store_type)
        if (value.version != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 27, value.version)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: File) {
        writer.writeBytes(value.unknownFields)
        if (value.version != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 27, value.version)
        if (value.store_type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 26, value.store_type)
        if (value.label != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 25, value.label)
        if (value.content_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 24,
            value.content_identity)
        if (value.unique != "") ProtoAdapter.STRING.encodeWithTag(writer, 23, value.unique)
        if (value.flag != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 22, value.flag)
        if (value.shared_at != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 21, value.shared_at)
        if (value.locked_by != "") ProtoAdapter.STRING.encodeWithTag(writer, 20, value.locked_by)
        if (value.locked_at != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 19, value.locked_at)
        if (value.trashed != false) ProtoAdapter.BOOL.encodeWithTag(writer, 18, value.trashed)
        if (value.starred != false) ProtoAdapter.BOOL.encodeWithTag(writer, 17, value.starred)
        if (value.shared != false) ProtoAdapter.BOOL.encodeWithTag(writer, 16, value.shared)
        if (value.locked != false) ProtoAdapter.BOOL.encodeWithTag(writer, 15, value.locked)
        if (value.hidden != false) ProtoAdapter.BOOL.encodeWithTag(writer, 14, value.hidden)
        if (value.dir != false) ProtoAdapter.BOOL.encodeWithTag(writer, 13, value.dir)
        if (value.deleted != false) ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.deleted)
        if (value.delete_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 11, value.delete_ts)
        if (value.update_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 10, value.update_ts)
        if (value.create_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 9, value.create_ts)
        if (value.type != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 8, value.type)
        if (value.size != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 7, value.size)
        if (value.mime_type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.mime_type)
        if (value.path != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.path)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.name)
        if (value.parent != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.parent)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
      }

      override fun decode(reader: ProtoReader): File {
        var identity: String = ""
        var parent: String = ""
        var name: String = ""
        var path: String = ""
        var mime_type: String = ""
        var size: Long = 0L
        var type: Long = 0L
        var create_ts: Long = 0L
        var update_ts: Long = 0L
        var delete_ts: Long = 0L
        var deleted: Boolean = false
        var dir: Boolean = false
        var hidden: Boolean = false
        var locked: Boolean = false
        var shared: Boolean = false
        var starred: Boolean = false
        var trashed: Boolean = false
        var locked_at: Long = 0L
        var locked_by: String = ""
        var shared_at: Long = 0L
        var flag: Long = 0L
        var unique: String = ""
        var content_identity: String = ""
        var label: Long = 0L
        var store_type: Long = 0L
        var version: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> identity = ProtoAdapter.STRING.decode(reader)
            3 -> parent = ProtoAdapter.STRING.decode(reader)
            4 -> name = ProtoAdapter.STRING.decode(reader)
            5 -> path = ProtoAdapter.STRING.decode(reader)
            6 -> mime_type = ProtoAdapter.STRING.decode(reader)
            7 -> size = ProtoAdapter.INT64.decode(reader)
            8 -> type = ProtoAdapter.INT64.decode(reader)
            9 -> create_ts = ProtoAdapter.INT64.decode(reader)
            10 -> update_ts = ProtoAdapter.INT64.decode(reader)
            11 -> delete_ts = ProtoAdapter.INT64.decode(reader)
            12 -> deleted = ProtoAdapter.BOOL.decode(reader)
            13 -> dir = ProtoAdapter.BOOL.decode(reader)
            14 -> hidden = ProtoAdapter.BOOL.decode(reader)
            15 -> locked = ProtoAdapter.BOOL.decode(reader)
            16 -> shared = ProtoAdapter.BOOL.decode(reader)
            17 -> starred = ProtoAdapter.BOOL.decode(reader)
            18 -> trashed = ProtoAdapter.BOOL.decode(reader)
            19 -> locked_at = ProtoAdapter.INT64.decode(reader)
            20 -> locked_by = ProtoAdapter.STRING.decode(reader)
            21 -> shared_at = ProtoAdapter.INT64.decode(reader)
            22 -> flag = ProtoAdapter.INT64.decode(reader)
            23 -> unique = ProtoAdapter.STRING.decode(reader)
            24 -> content_identity = ProtoAdapter.STRING.decode(reader)
            25 -> label = ProtoAdapter.INT64.decode(reader)
            26 -> store_type = ProtoAdapter.INT64.decode(reader)
            27 -> version = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return File(
          identity = identity,
          parent = parent,
          name = name,
          path = path,
          mime_type = mime_type,
          size = size,
          type = type,
          create_ts = create_ts,
          update_ts = update_ts,
          delete_ts = delete_ts,
          deleted = deleted,
          dir = dir,
          hidden = hidden,
          locked = locked,
          shared = shared,
          starred = starred,
          trashed = trashed,
          locked_at = locked_at,
          locked_by = locked_by,
          shared_at = shared_at,
          flag = flag,
          unique = unique,
          content_identity = content_identity,
          label = label,
          store_type = store_type,
          version = version,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: File): File = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
