// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.GetIceCandidateResponse in public_user_file.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class GetIceCandidateResponse(
  /**
   * string content_identity = 1;
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "clientIdentity",
    schemaIndex = 0,
  )
  public val client_identity: String = "",
  candidate: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GetIceCandidateResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val candidate: List<String> = immutableCopyOf("candidate", candidate)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GetIceCandidateResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (client_identity != other.client_identity) return false
    if (candidate != other.candidate) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + client_identity.hashCode()
      result = result * 37 + candidate.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """client_identity=${sanitize(client_identity)}"""
    if (candidate.isNotEmpty()) result += """candidate=${sanitize(candidate)}"""
    return result.joinToString(prefix = "GetIceCandidateResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    client_identity: String = this.client_identity,
    candidate: List<String> = this.candidate,
    unknownFields: ByteString = this.unknownFields,
  ): GetIceCandidateResponse = GetIceCandidateResponse(client_identity, candidate, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GetIceCandidateResponse> = object :
        ProtoAdapter<GetIceCandidateResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      GetIceCandidateResponse::class, 
      "type.googleapis.com/v6.services.pub.GetIceCandidateResponse", 
      PROTO_3, 
      null, 
      "public_user_file.proto"
    ) {
      override fun encodedSize(`value`: GetIceCandidateResponse): Int {
        var size = value.unknownFields.size
        if (value.client_identity != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.client_identity)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.candidate)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GetIceCandidateResponse) {
        if (value.client_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.client_identity)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.candidate)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GetIceCandidateResponse) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.candidate)
        if (value.client_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.client_identity)
      }

      override fun decode(reader: ProtoReader): GetIceCandidateResponse {
        var client_identity: String = ""
        val candidate = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> client_identity = ProtoAdapter.STRING.decode(reader)
            2 -> candidate.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return GetIceCandidateResponse(
          client_identity = client_identity,
          candidate = candidate,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GetIceCandidateResponse): GetIceCandidateResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
