// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.PubDavConfig in public_webdav.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import kotlin.Suppress
import api.v6.services.pub.common.UserNameValidateResponse

public class GrpcPubDavConfigClient(
  private val client: GrpcClient,
) : PubDavConfigClient {
  /**
   * rpc Create (DavConfig) returns (DavConfig) {}
   */
  override fun Get(): GrpcCall<DavConfig, DavConfig> = client.newCall(GrpcMethod(
      path = "/v6.services.pub.PubDavConfig/Get",
      requestAdapter = DavConfig.ADAPTER,
      responseAdapter = DavConfig.ADAPTER
  ))

  override fun Update(): GrpcCall<DavConfig, DavConfig> = client.newCall(GrpcMethod(
      path = "/v6.services.pub.PubDavConfig/Update",
      requestAdapter = DavConfig.ADAPTER,
      responseAdapter = DavConfig.ADAPTER
  ))

  override fun Enable(): GrpcCall<DavConfig, DavConfig> = client.newCall(GrpcMethod(
      path = "/v6.services.pub.PubDavConfig/Enable",
      requestAdapter = DavConfig.ADAPTER,
      responseAdapter = DavConfig.ADAPTER
  ))

  override fun Disable(): GrpcCall<DavConfig, DavConfig> = client.newCall(GrpcMethod(
      path = "/v6.services.pub.PubDavConfig/Disable",
      requestAdapter = DavConfig.ADAPTER,
      responseAdapter = DavConfig.ADAPTER
  ))

  override fun ValidateUserName(): GrpcCall<DavConfig, UserNameValidateResponse> =
      client.newCall(GrpcMethod(
      path = "/v6.services.pub.PubDavConfig/ValidateUserName",
      requestAdapter = DavConfig.ADAPTER,
      responseAdapter = UserNameValidateResponse.ADAPTER
  ))
}
