// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.LastLoginResponse in user_svc.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class LastLoginResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val identity: String = "",
  /**
   * millisecond
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastLoginTs",
    schemaIndex = 1,
  )
  public val last_login_ts: Long = 0L,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastLoginIp",
    schemaIndex = 2,
  )
  public val last_login_ip: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastLoginDevice",
    schemaIndex = 3,
  )
  public val last_login_device: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LastLoginResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LastLoginResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (identity != other.identity) return false
    if (last_login_ts != other.last_login_ts) return false
    if (last_login_ip != other.last_login_ip) return false
    if (last_login_device != other.last_login_device) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + identity.hashCode()
      result = result * 37 + last_login_ts.hashCode()
      result = result * 37 + last_login_ip.hashCode()
      result = result * 37 + last_login_device.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """identity=${sanitize(identity)}"""
    result += """last_login_ts=$last_login_ts"""
    result += """last_login_ip=${sanitize(last_login_ip)}"""
    result += """last_login_device=${sanitize(last_login_device)}"""
    return result.joinToString(prefix = "LastLoginResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    identity: String = this.identity,
    last_login_ts: Long = this.last_login_ts,
    last_login_ip: String = this.last_login_ip,
    last_login_device: String = this.last_login_device,
    unknownFields: ByteString = this.unknownFields,
  ): LastLoginResponse = LastLoginResponse(identity, last_login_ts, last_login_ip,
      last_login_device, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LastLoginResponse> = object : ProtoAdapter<LastLoginResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      LastLoginResponse::class, 
      "type.googleapis.com/v6.services.pub.LastLoginResponse", 
      PROTO_3, 
      null, 
      "user_svc.proto"
    ) {
      override fun encodedSize(`value`: LastLoginResponse): Int {
        var size = value.unknownFields.size
        if (value.identity != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.identity)
        if (value.last_login_ts != 0L) size += ProtoAdapter.INT64.encodedSizeWithTag(2,
            value.last_login_ts)
        if (value.last_login_ip != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3,
            value.last_login_ip)
        if (value.last_login_device != "") size += ProtoAdapter.STRING.encodedSizeWithTag(4,
            value.last_login_device)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LastLoginResponse) {
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
        if (value.last_login_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 2,
            value.last_login_ts)
        if (value.last_login_ip != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.last_login_ip)
        if (value.last_login_device != "") ProtoAdapter.STRING.encodeWithTag(writer, 4,
            value.last_login_device)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LastLoginResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.last_login_device != "") ProtoAdapter.STRING.encodeWithTag(writer, 4,
            value.last_login_device)
        if (value.last_login_ip != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.last_login_ip)
        if (value.last_login_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 2,
            value.last_login_ts)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
      }

      override fun decode(reader: ProtoReader): LastLoginResponse {
        var identity: String = ""
        var last_login_ts: Long = 0L
        var last_login_ip: String = ""
        var last_login_device: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> identity = ProtoAdapter.STRING.decode(reader)
            2 -> last_login_ts = ProtoAdapter.INT64.decode(reader)
            3 -> last_login_ip = ProtoAdapter.STRING.decode(reader)
            4 -> last_login_device = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LastLoginResponse(
          identity = identity,
          last_login_ts = last_login_ts,
          last_login_ip = last_login_ip,
          last_login_device = last_login_device,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LastLoginResponse): LastLoginResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
