// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.OfflineTaskDeleteResponse in public_user_offline.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class OfflineTaskDeleteResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val count: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<OfflineTaskDeleteResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is OfflineTaskDeleteResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (count != other.count) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + count.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """count=$count"""
    return result.joinToString(prefix = "OfflineTaskDeleteResponse{", separator = ", ", postfix =
        "}")
  }

  public fun copy(count: Long = this.count, unknownFields: ByteString = this.unknownFields):
      OfflineTaskDeleteResponse = OfflineTaskDeleteResponse(count, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<OfflineTaskDeleteResponse> = object :
        ProtoAdapter<OfflineTaskDeleteResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      OfflineTaskDeleteResponse::class, 
      "type.googleapis.com/v6.services.pub.OfflineTaskDeleteResponse", 
      PROTO_3, 
      null, 
      "public_user_offline.proto"
    ) {
      override fun encodedSize(`value`: OfflineTaskDeleteResponse): Int {
        var size = value.unknownFields.size
        if (value.count != 0L) size += ProtoAdapter.INT64.encodedSizeWithTag(1, value.count)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: OfflineTaskDeleteResponse) {
        if (value.count != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.count)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: OfflineTaskDeleteResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.count != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.count)
      }

      override fun decode(reader: ProtoReader): OfflineTaskDeleteResponse {
        var count: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> count = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return OfflineTaskDeleteResponse(
          count = count,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: OfflineTaskDeleteResponse): OfflineTaskDeleteResponse =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
