// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.PubSlice in slice_svc.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress

public interface PubSliceClient : Service {
  public fun GetSlice(): GrpcCall<Slice, Slice>

  public fun CreateSlice(): GrpcCall<Slice, Slice>

  public fun GetMeta(): GrpcCall<Meta, Meta>

  public fun CreateMeta(): GrpcCall<Meta, Meta>

  public fun AddFastLookup(): GrpcCall<FastLookup, FastLookup>

  public fun GetFastLookup(): GrpcCall<FastLookupRequest, FastLookup>
}
