// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.PubUserFile in public_user_file.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress

public interface PubUserFileClient : Service {
  public fun Create(): GrpcCall<File, File>

  public fun Get(): GrpcCall<File, File>

  /**
   * rpc Update (File) returns (File) {}
   */
  public fun Rename(): GrpcCall<File, BatchOperationResponse>

  public fun Trash(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun Move(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun Copy(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun Delete(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun DeleteTrash(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun Recover(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun BatchOperation(): GrpcCall<BatchOperationRequest, BatchOperationResponse>

  public fun List(): GrpcCall<FileListRequest, FileListResponse>

  public fun ListTrash(): GrpcCall<FileListRequest, FileListResponse>

  public fun Search(): GrpcCall<SearchRequest, FileListResponse>

  public fun CreateManageRTCOffer(): GrpcCall<ManageRTCRequest, ManageRTCResponse>

  public fun SendClientIceCandidate(): GrpcCall<SendIceCandidateRequest, SendIceCandidateResponse>

  public fun GetServerIceCandidate(): GrpcCall<GetIceCandidateRequest, GetIceCandidateResponse>

  public fun ParseFileSlice(): GrpcCall<File, ParseFileSliceResponse>

  public fun GetSliceDownloadAddress():
      GrpcCall<SliceDownloadAddressRequest, SliceDownloadAddressResponse>

  public fun GetDownloadAndPreviewInfo(): GrpcCall<File, DownloadAndPreviewInfo>

  public fun PreviewDoc(): GrpcCall<File, DocFilePreview>

  public fun CreateDoc(): GrpcCall<File, DocFilePreview>

  public fun CreateUploadToken(): GrpcCall<File, UploadToken>
}
