// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.SliceDownloadAddressResponse in public_user_file.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class SliceDownloadAddressResponse(
  addresses: List<SliceDownloadInfo> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "expireAt",
    schemaIndex = 1,
  )
  public val expire_at: Long = 0L,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestAddress",
    schemaIndex = 2,
  )
  public val request_address: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val version: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SliceDownloadAddressResponse, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "v6.services.pub.SliceDownloadInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val addresses: List<SliceDownloadInfo> = immutableCopyOf("addresses", addresses)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SliceDownloadAddressResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (addresses != other.addresses) return false
    if (expire_at != other.expire_at) return false
    if (request_address != other.request_address) return false
    if (version != other.version) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + addresses.hashCode()
      result = result * 37 + expire_at.hashCode()
      result = result * 37 + request_address.hashCode()
      result = result * 37 + version.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (addresses.isNotEmpty()) result += """addresses=$addresses"""
    result += """expire_at=$expire_at"""
    result += """request_address=${sanitize(request_address)}"""
    result += """version=$version"""
    return result.joinToString(prefix = "SliceDownloadAddressResponse{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    addresses: List<SliceDownloadInfo> = this.addresses,
    expire_at: Long = this.expire_at,
    request_address: String = this.request_address,
    version: Int = this.version,
    unknownFields: ByteString = this.unknownFields,
  ): SliceDownloadAddressResponse = SliceDownloadAddressResponse(addresses, expire_at,
      request_address, version, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SliceDownloadAddressResponse> = object :
        ProtoAdapter<SliceDownloadAddressResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SliceDownloadAddressResponse::class, 
      "type.googleapis.com/v6.services.pub.SliceDownloadAddressResponse", 
      PROTO_3, 
      null, 
      "public_user_file.proto"
    ) {
      override fun encodedSize(`value`: SliceDownloadAddressResponse): Int {
        var size = value.unknownFields.size
        size += SliceDownloadInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.addresses)
        if (value.expire_at != 0L) size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.expire_at)
        if (value.request_address != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3,
            value.request_address)
        if (value.version != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.version)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SliceDownloadAddressResponse) {
        SliceDownloadInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.addresses)
        if (value.expire_at != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.expire_at)
        if (value.request_address != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.request_address)
        if (value.version != 0) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.version)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SliceDownloadAddressResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.version != 0) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.version)
        if (value.request_address != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.request_address)
        if (value.expire_at != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 2, value.expire_at)
        SliceDownloadInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.addresses)
      }

      override fun decode(reader: ProtoReader): SliceDownloadAddressResponse {
        val addresses = mutableListOf<SliceDownloadInfo>()
        var expire_at: Long = 0L
        var request_address: String = ""
        var version: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> addresses.add(SliceDownloadInfo.ADAPTER.decode(reader))
            2 -> expire_at = ProtoAdapter.INT64.decode(reader)
            3 -> request_address = ProtoAdapter.STRING.decode(reader)
            4 -> version = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SliceDownloadAddressResponse(
          addresses = addresses,
          expire_at = expire_at,
          request_address = request_address,
          version = version,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SliceDownloadAddressResponse): SliceDownloadAddressResponse =
          value.copy(
        addresses = value.addresses.redactElements(SliceDownloadInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
