// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.SmsVeifyCodeSendResponse in user_svc.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class SmsVeifyCodeSendResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val captcha: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val type: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val addon: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "expireTs",
    schemaIndex = 3,
  )
  public val expire_ts: Long = 0L,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SmsVeifyCodeSendResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SmsVeifyCodeSendResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (captcha != other.captcha) return false
    if (type != other.type) return false
    if (addon != other.addon) return false
    if (expire_ts != other.expire_ts) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + captcha.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + addon.hashCode()
      result = result * 37 + expire_ts.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """captcha=${sanitize(captcha)}"""
    result += """type=$type"""
    result += """addon=${sanitize(addon)}"""
    result += """expire_ts=$expire_ts"""
    return result.joinToString(prefix = "SmsVeifyCodeSendResponse{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    captcha: String = this.captcha,
    type: Int = this.type,
    addon: String = this.addon,
    expire_ts: Long = this.expire_ts,
    unknownFields: ByteString = this.unknownFields,
  ): SmsVeifyCodeSendResponse = SmsVeifyCodeSendResponse(captcha, type, addon, expire_ts,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SmsVeifyCodeSendResponse> = object :
        ProtoAdapter<SmsVeifyCodeSendResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      SmsVeifyCodeSendResponse::class, 
      "type.googleapis.com/v6.services.pub.SmsVeifyCodeSendResponse", 
      PROTO_3, 
      null, 
      "user_svc.proto"
    ) {
      override fun encodedSize(`value`: SmsVeifyCodeSendResponse): Int {
        var size = value.unknownFields.size
        if (value.captcha != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.captcha)
        if (value.type != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.type)
        if (value.addon != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.addon)
        if (value.expire_ts != 0L) size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.expire_ts)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SmsVeifyCodeSendResponse) {
        if (value.captcha != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.captcha)
        if (value.type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.type)
        if (value.addon != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.addon)
        if (value.expire_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 4, value.expire_ts)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SmsVeifyCodeSendResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.expire_ts != 0L) ProtoAdapter.INT64.encodeWithTag(writer, 4, value.expire_ts)
        if (value.addon != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.addon)
        if (value.type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.type)
        if (value.captcha != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.captcha)
      }

      override fun decode(reader: ProtoReader): SmsVeifyCodeSendResponse {
        var captcha: String = ""
        var type: Int = 0
        var addon: String = ""
        var expire_ts: Long = 0L
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> captcha = ProtoAdapter.STRING.decode(reader)
            2 -> type = ProtoAdapter.INT32.decode(reader)
            3 -> addon = ProtoAdapter.STRING.decode(reader)
            4 -> expire_ts = ProtoAdapter.INT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SmsVeifyCodeSendResponse(
          captcha = captcha,
          type = type,
          addon = addon,
          expire_ts = expire_ts,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SmsVeifyCodeSendResponse): SmsVeifyCodeSendResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
