// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.SmsVeifyCodeSendRequestNotUser in user_svc.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class SmsVeifyCodeSendRequestNotUser(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val captcha: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val type: Int = 0,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val addon: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "countryCode",
    schemaIndex = 3,
  )
  public val country_code: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val phone: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<SmsVeifyCodeSendRequestNotUser, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SmsVeifyCodeSendRequestNotUser) return false
    if (unknownFields != other.unknownFields) return false
    if (captcha != other.captcha) return false
    if (type != other.type) return false
    if (addon != other.addon) return false
    if (country_code != other.country_code) return false
    if (phone != other.phone) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + captcha.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + addon.hashCode()
      result = result * 37 + country_code.hashCode()
      result = result * 37 + phone.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """captcha=${sanitize(captcha)}"""
    result += """type=$type"""
    result += """addon=${sanitize(addon)}"""
    result += """country_code=${sanitize(country_code)}"""
    result += """phone=${sanitize(phone)}"""
    return result.joinToString(prefix = "SmsVeifyCodeSendRequestNotUser{", separator = ", ", postfix
        = "}")
  }

  public fun copy(
    captcha: String = this.captcha,
    type: Int = this.type,
    addon: String = this.addon,
    country_code: String = this.country_code,
    phone: String = this.phone,
    unknownFields: ByteString = this.unknownFields,
  ): SmsVeifyCodeSendRequestNotUser = SmsVeifyCodeSendRequestNotUser(captcha, type, addon,
      country_code, phone, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SmsVeifyCodeSendRequestNotUser> = object :
        ProtoAdapter<SmsVeifyCodeSendRequestNotUser>(
      FieldEncoding.LENGTH_DELIMITED, 
      SmsVeifyCodeSendRequestNotUser::class, 
      "type.googleapis.com/v6.services.pub.SmsVeifyCodeSendRequestNotUser", 
      PROTO_3, 
      null, 
      "user_svc.proto"
    ) {
      override fun encodedSize(`value`: SmsVeifyCodeSendRequestNotUser): Int {
        var size = value.unknownFields.size
        if (value.captcha != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.captcha)
        if (value.type != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.type)
        if (value.addon != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.addon)
        if (value.country_code != "") size += ProtoAdapter.STRING.encodedSizeWithTag(4,
            value.country_code)
        if (value.phone != "") size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.phone)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SmsVeifyCodeSendRequestNotUser) {
        if (value.captcha != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.captcha)
        if (value.type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.type)
        if (value.addon != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.addon)
        if (value.country_code != "") ProtoAdapter.STRING.encodeWithTag(writer, 4,
            value.country_code)
        if (value.phone != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.phone)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SmsVeifyCodeSendRequestNotUser) {
        writer.writeBytes(value.unknownFields)
        if (value.phone != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.phone)
        if (value.country_code != "") ProtoAdapter.STRING.encodeWithTag(writer, 4,
            value.country_code)
        if (value.addon != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.addon)
        if (value.type != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.type)
        if (value.captcha != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.captcha)
      }

      override fun decode(reader: ProtoReader): SmsVeifyCodeSendRequestNotUser {
        var captcha: String = ""
        var type: Int = 0
        var addon: String = ""
        var country_code: String = ""
        var phone: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> captcha = ProtoAdapter.STRING.decode(reader)
            2 -> type = ProtoAdapter.INT32.decode(reader)
            3 -> addon = ProtoAdapter.STRING.decode(reader)
            4 -> country_code = ProtoAdapter.STRING.decode(reader)
            5 -> phone = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SmsVeifyCodeSendRequestNotUser(
          captcha = captcha,
          type = type,
          addon = addon,
          country_code = country_code,
          phone = phone,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SmsVeifyCodeSendRequestNotUser): SmsVeifyCodeSendRequestNotUser =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
