// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.TaskParseRequest in public_user_offline.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class TaskParseRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val url: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "file",
    schemaIndex = 1,
  )
  public val file_: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val identity: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TaskParseRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TaskParseRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (url != other.url) return false
    if (file_ != other.file_) return false
    if (identity != other.identity) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + file_.hashCode()
      result = result * 37 + identity.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """url=${sanitize(url)}"""
    result += """file_=${sanitize(file_)}"""
    result += """identity=${sanitize(identity)}"""
    return result.joinToString(prefix = "TaskParseRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    url: String = this.url,
    file_: String = this.file_,
    identity: String = this.identity,
    unknownFields: ByteString = this.unknownFields,
  ): TaskParseRequest = TaskParseRequest(url, file_, identity, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TaskParseRequest> = object : ProtoAdapter<TaskParseRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      TaskParseRequest::class, 
      "type.googleapis.com/v6.services.pub.TaskParseRequest", 
      PROTO_3, 
      null, 
      "public_user_offline.proto"
    ) {
      override fun encodedSize(`value`: TaskParseRequest): Int {
        var size = value.unknownFields.size
        if (value.url != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.url)
        if (value.file_ != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.file_)
        if (value.identity != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.identity)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TaskParseRequest) {
        if (value.url != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
        if (value.file_ != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.file_)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.identity)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TaskParseRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.identity)
        if (value.file_ != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.file_)
        if (value.url != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url)
      }

      override fun decode(reader: ProtoReader): TaskParseRequest {
        var url: String = ""
        var file_: String = ""
        var identity: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> url = ProtoAdapter.STRING.decode(reader)
            2 -> file_ = ProtoAdapter.STRING.decode(reader)
            3 -> identity = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TaskParseRequest(
          url = url,
          file_ = file_,
          identity = identity,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TaskParseRequest): TaskParseRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
