// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.pub.UserValidateInfo in user_svc.proto
@file:Suppress("DEPRECATION")

package api.v6.services.pub

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class UserValidateInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val identity: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val name: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val email: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val phone: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "countryCode",
    schemaIndex = 4,
  )
  public val country_code: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val addon: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<UserValidateInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UserValidateInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (identity != other.identity) return false
    if (name != other.name) return false
    if (email != other.email) return false
    if (phone != other.phone) return false
    if (country_code != other.country_code) return false
    if (addon != other.addon) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + identity.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + email.hashCode()
      result = result * 37 + phone.hashCode()
      result = result * 37 + country_code.hashCode()
      result = result * 37 + addon.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """identity=${sanitize(identity)}"""
    result += """name=${sanitize(name)}"""
    result += """email=${sanitize(email)}"""
    result += """phone=${sanitize(phone)}"""
    result += """country_code=${sanitize(country_code)}"""
    result += """addon=${sanitize(addon)}"""
    return result.joinToString(prefix = "UserValidateInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    identity: String = this.identity,
    name: String = this.name,
    email: String = this.email,
    phone: String = this.phone,
    country_code: String = this.country_code,
    addon: String = this.addon,
    unknownFields: ByteString = this.unknownFields,
  ): UserValidateInfo = UserValidateInfo(identity, name, email, phone, country_code, addon,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UserValidateInfo> = object : ProtoAdapter<UserValidateInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      UserValidateInfo::class, 
      "type.googleapis.com/v6.services.pub.UserValidateInfo", 
      PROTO_3, 
      null, 
      "user_svc.proto"
    ) {
      override fun encodedSize(`value`: UserValidateInfo): Int {
        var size = value.unknownFields.size
        if (value.identity != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.identity)
        if (value.name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name)
        if (value.email != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.email)
        if (value.phone != "") size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.phone)
        if (value.country_code != "") size += ProtoAdapter.STRING.encodedSizeWithTag(5,
            value.country_code)
        if (value.addon != "") size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.addon)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UserValidateInfo) {
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        if (value.email != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.email)
        if (value.phone != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.phone)
        if (value.country_code != "") ProtoAdapter.STRING.encodeWithTag(writer, 5,
            value.country_code)
        if (value.addon != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.addon)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UserValidateInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.addon != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.addon)
        if (value.country_code != "") ProtoAdapter.STRING.encodeWithTag(writer, 5,
            value.country_code)
        if (value.phone != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.phone)
        if (value.email != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.email)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        if (value.identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.identity)
      }

      override fun decode(reader: ProtoReader): UserValidateInfo {
        var identity: String = ""
        var name: String = ""
        var email: String = ""
        var phone: String = ""
        var country_code: String = ""
        var addon: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> identity = ProtoAdapter.STRING.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> email = ProtoAdapter.STRING.decode(reader)
            4 -> phone = ProtoAdapter.STRING.decode(reader)
            5 -> country_code = ProtoAdapter.STRING.decode(reader)
            6 -> addon = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UserValidateInfo(
          identity = identity,
          name = name,
          email = email,
          phone = phone,
          country_code = country_code,
          addon = addon,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UserValidateInfo): UserValidateInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
