// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.p2p.ReceiveRequest in webrtc_manager.proto
@file:Suppress("DEPRECATION")

package api.v6.services.p2p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ReceiveRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ReceiveRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ReceiveRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    return result.joinToString(prefix = "ReceiveRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(id: String = this.id, unknownFields: ByteString = this.unknownFields):
      ReceiveRequest = ReceiveRequest(id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ReceiveRequest> = object : ProtoAdapter<ReceiveRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ReceiveRequest::class, 
      "type.googleapis.com/v6.services.p2p.ReceiveRequest", 
      PROTO_3, 
      null, 
      "webrtc_manager.proto"
    ) {
      override fun encodedSize(`value`: ReceiveRequest): Int {
        var size = value.unknownFields.size
        if (value.id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ReceiveRequest) {
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ReceiveRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
      }

      override fun decode(reader: ProtoReader): ReceiveRequest {
        var id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ReceiveRequest(
          id = id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ReceiveRequest): ReceiveRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
