// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.services.p2p.StopDownloadRequest in webrtc_manager.proto
@file:Suppress("DEPRECATION")

package api.v6.services.p2p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class StopDownloadRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "clientIdentity",
    schemaIndex = 0,
  )
  public val client_identity: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contentIdentity",
    schemaIndex = 1,
  )
  public val content_identity: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StopDownloadRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StopDownloadRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (client_identity != other.client_identity) return false
    if (content_identity != other.content_identity) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + client_identity.hashCode()
      result = result * 37 + content_identity.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """client_identity=${sanitize(client_identity)}"""
    result += """content_identity=${sanitize(content_identity)}"""
    return result.joinToString(prefix = "StopDownloadRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    client_identity: String = this.client_identity,
    content_identity: String = this.content_identity,
    unknownFields: ByteString = this.unknownFields,
  ): StopDownloadRequest = StopDownloadRequest(client_identity, content_identity, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StopDownloadRequest> = object :
        ProtoAdapter<StopDownloadRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StopDownloadRequest::class, 
      "type.googleapis.com/v6.services.p2p.StopDownloadRequest", 
      PROTO_3, 
      null, 
      "webrtc_manager.proto"
    ) {
      override fun encodedSize(`value`: StopDownloadRequest): Int {
        var size = value.unknownFields.size
        if (value.client_identity != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.client_identity)
        if (value.content_identity != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.content_identity)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StopDownloadRequest) {
        if (value.client_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.client_identity)
        if (value.content_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.content_identity)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StopDownloadRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.content_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.content_identity)
        if (value.client_identity != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.client_identity)
      }

      override fun decode(reader: ProtoReader): StopDownloadRequest {
        var client_identity: String = ""
        var content_identity: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> client_identity = ProtoAdapter.STRING.decode(reader)
            2 -> content_identity = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StopDownloadRequest(
          client_identity = client_identity,
          content_identity = content_identity,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StopDownloadRequest): StopDownloadRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
