// Code generated by Wire protocol buffer compiler, do not edit.
// Source: v6.rpc.RpcHeaderValue in rpc_transport.proto
@file:Suppress("DEPRECATION")

package api.v6.rpc

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class RpcHeaderValue(
  value_: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<RpcHeaderValue, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: List<String> = immutableCopyOf("value_", value_)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RpcHeaderValue) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + value_.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (value_.isNotEmpty()) result += """value_=${sanitize(value_)}"""
    return result.joinToString(prefix = "RpcHeaderValue{", separator = ", ", postfix = "}")
  }

  public fun copy(value_: List<String> = this.value_, unknownFields: ByteString =
      this.unknownFields): RpcHeaderValue = RpcHeaderValue(value_, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RpcHeaderValue> = object : ProtoAdapter<RpcHeaderValue>(
      FieldEncoding.LENGTH_DELIMITED, 
      RpcHeaderValue::class, 
      "type.googleapis.com/v6.rpc.RpcHeaderValue", 
      PROTO_3, 
      null, 
      "rpc_transport.proto"
    ) {
      override fun encodedSize(`value`: RpcHeaderValue): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.value_)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RpcHeaderValue) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.value_)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RpcHeaderValue) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.value_)
      }

      override fun decode(reader: ProtoReader): RpcHeaderValue {
        val value_ = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return RpcHeaderValue(
          value_ = value_,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RpcHeaderValue): RpcHeaderValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
